[package]
name = "small_os"
version = "0.1.0"
authors = ["Mayeul Fournial <mfournial@outlook.com>"]
edition = "2018"

[package.metadata.bootimage]
default-target = "x86_64.json"

[dependencies]
bootloader = "0.3.12"
volatile = "0.2.3"