[package]
name = "small_os"
version = "0.1.0"
authors = ["Mayeul Fournial <mfournial@outlook.com>"]
edition = "2018"

# Disables stack unwinding
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
